name: toastrx_flutter
description: A customizable toast notification package for Flutter apps with clean UI and support for multiple toast styles.
version: 0.0.1
homepage: https://github.com/AaryanSharmaNeupane/toastr
repository: https://github.com/AaryanSharmaNeupane/toastr
topics:
  - toast
  - toastrx_flutter
  - message
  - notification
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
